export const LAUNCH_MODES = {
  DIRECT_MARKET: "DIRECT_MARKET",
  BONDING_CURVE: "BONDING_CURVE",
};

export const BONDING_CURVE_TYPES = {
  LINEAR: "LINEAR",
  EXPONENTIAL: "EXPONENTIAL",
  CONSTANT_PRODUCT: "CONSTANT_PRODUCT",
};

export const PROTOCOL_FEES = {
  DEFAULT_LAUNCH_FEE_NEAR: "0.2",

  TRADING_FEE_PLATFORM_BPS: 3000,
  TRADING_FEE_CREATOR_BPS: 7000,

  TAX_PLATFORM_BPS: 4000,
  TAX_CREATOR_BPS: 6000,

  MAX_BUY_TAX_BPS: 500,
  MAX_SELL_TAX_BPS: 100,
};
export const LAUNCH_STATUS = {
  DRAFT: "DRAFT",
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",

  GRADUATION_THRESHOLD_REACHED: "GRADUATION_THRESHOLD_REACHED",

  GRADUATING: "GRADUATING",

  GRADUATED: "GRADUATED",

  COMPLETED: "COMPLETED",

  CANCELLED: "CANCELLED",

  FAILED: "FAILED",
};
